### ISSUE TITLE
Chattix Enables Server Previewing

### ISSUE THREAD

**Issue by TheFallenChaos** [PlanetTeamSpeakk/Chattix#4]
Hi!
I'm not sure as to why this happens, but server previewing is still enabled despite having it disabled, when Chattix is added.
![image](https://user-images.githubusercontent.com/74574396/198155245-da5be4b9-b429-414d-b5b1-cf2c9da7475b.png)

Is this possible to be fixed?

**Comment by PlanetTeamSpeakk** [comment]
This behaviour is intended as it is required to be enabled if you want the messages to be formatted. It is not possible to format messages without then being previewed as it will show up for every player as being unlawfully modified by the server (that meaning, the server changed the message without the sender knowing beforehand how they'd change it).
That said, the only way to disable this is by disabling the chat formatting feature.
