### ISSUE TITLE
Website not working (https://chattix.ptsmods.com)

### ISSUE THREAD

**Issue by FloofyCandy** [PlanetTeamSpeakk/Chattix#8]
Hello, just wanted to say this is an amazing mod. I am trying to see the list of placeholders available for chat formatting but the website doesn't load saying that the "DNS address could not be found". Is there anywhere else I can find the placeholders?

**Comment by PlanetTeamSpeakk** [comment]
I have not yet made any docs. Just didn't come around to it yet, but I will later.

**Comment by FloofyCandy** [comment]
Alright, thank you.
