### ISSUE TITLE
Custom achievements don't get logged to chat

### ISSUE THREAD

**Issue by ChristopherHaws** [PlanetTeamSpeakk/Chattix#9]
I am using the Create mod which has custom achievements. When I unlock one it shows me the popup window but nothing gets logged to chat.

**Comment by PlanetTeamSpeakk** [comment]
And it does get logged without Chattix? Because I cannot see how Chattix might interfere with this.

**Comment by ChristopherHaws** [comment]
I will double check later tonight, but I am pretty sure it does. It behaves just like vanilla achievements as far as I can tell.

**Comment by PlanetTeamSpeakk** [comment]
Closed due to lack of context.
